name: Unity Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# also please enable GitHub Pages in the repository settings
# https://github.com/hchan/DinerPhilosophersGame/settings/pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Set up Unity
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
    
      # Inspect the build
      - name: Inspect Build
        run: |
          echo "Inspecting build..."
          # Add your inspection commands here
          # For example, you can list the contents of the build directory
          find build/WebGL
          # example output
            # build/WebGL
            # build/WebGL/WebGL
            # build/WebGL/WebGL/index.html
            # build/WebGL/WebGL/TemplateData
            # build/WebGL/WebGL/TemplateData/MemoryProfiler.png
            # build/WebGL/WebGL/TemplateData/style.css
            # build/WebGL/WebGL/TemplateData/progress-bar-empty-dark.png
            # build/WebGL/WebGL/TemplateData/progress-bar-full-light.png
            # build/WebGL/WebGL/TemplateData/fullscreen-button.png
            # build/WebGL/WebGL/TemplateData/progress-bar-empty-light.png
            # build/WebGL/WebGL/TemplateData/favicon.ico
            # build/WebGL/WebGL/TemplateData/unity-logo-light.png
            # build/WebGL/WebGL/TemplateData/webmemd-icon.png
            # build/WebGL/WebGL/TemplateData/progress-bar-full-dark.png
            # build/WebGL/WebGL/TemplateData/unity-logo-title-footer.png
            # build/WebGL/WebGL/TemplateData/unity-logo-dark.png
            # build/WebGL/WebGL/Build
            # build/WebGL/WebGL/Build/WebGL.wasm.br
            # build/WebGL/WebGL/Build/WebGL.framework.js.br
            # build/WebGL/WebGL/Build/WebGL.loader.js
            # build/WebGL/WebGL/Build/WebGL.data.br



      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: build/WebGL/WebGL
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
