name: Unity Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
            path: Library
            key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
            restore-keys: |
                Library-        

      # Set up Unity
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL



      # Cache the Unity build
      - name: Cache Unity packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/unity3d
          key: ${{ runner.os }}-unity-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-unity-

      # Output
    #   - uses: actions/upload-artifact@v3
    #     with:
    #         name: Build
    #         path: build
